In [1]:
import numpy as np
import tensorflow as tf

In [2]:
with open("/content/The_University_of_Colombo.txt", 'r', encoding='utf-8') as file:
    The_University_of_Colombo = file.read()

In [3]:
The_University_of_Colombo[:500]

'The University of Colombo (informally Colombo University or UOC) is a public research university located primarily in Colombo, Sri Lanka. It is the oldest institution of modern higher education in Sri Lanka. Specialized in the fields of natural, social, and applied sciences as well as mathematics, computer sciences, and law. It is ranked among the top 10 universities in South Asia.\n\nThe University of Colombo was founded in 1921 as University College Colombo, affiliated to the University of Londo'

In [4]:
tokenizer = tf.keras.preprocessing.text.Tokenizer()
tokenizer.fit_on_texts([The_University_of_Colombo])

In [5]:
tokenizer.get_config()['filters']

'!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n'

In [6]:
tokenizer.get_config()['word_counts']

'{"the": 238, "university": 83, "of": 163, "colombo": 38, "informally": 1, "or": 3, "uoc": 4, "is": 25, "a": 23, "public": 2, "research": 4, "located": 10, "primarily": 1, "in": 81, "sri": 17, "lanka": 14, "it": 14, "oldest": 7, "institution": 3, "modern": 1, "higher": 1, "education": 6, "specialized": 1, "fields": 3, "natural": 1, "social": 1, "and": 75, "applied": 1, "sciences": 4, "as": 21, "well": 2, "mathematics": 4, "computer": 4, "law": 16, "ranked": 1, "among": 2, "top": 1, "10": 3, "universities": 5, "south": 2, "asia": 2, "was": 35, "founded": 2, "1921": 2, "college": 24, "affiliated": 5, "to": 33, "london": 3, "degrees": 5, "were": 10, "issued": 1, "its": 17, "students": 7, "from": 5, "1923": 1, "onwards": 1, "traces": 1, "roots": 1, "1870": 4, "when": 3, "ceylon": 23, "medical": 12, "school": 10, "established": 16, "has": 10, "produced": 1, "notable": 1, "alumni": 1, "science": 18, "economics": 1, "business": 1, "literature": 1, "politics": 1, "state": 3, "with": 22, "most"

In [7]:
tokenizer.word_index

{'the': 1,
 'of': 2,
 'university': 3,
 'in': 4,
 'and': 5,
 'faculty': 6,
 'colombo': 7,
 'was': 8,
 'to': 9,
 'is': 10,
 'college': 11,
 'a': 12,
 'ceylon': 13,
 'with': 14,
 'as': 15,
 'science': 16,
 'sri': 17,
 'its': 18,
 'law': 19,
 'established': 20,
 'by': 21,
 'at': 22,
 'department': 23,
 'lanka': 24,
 'it': 25,
 'are': 26,
 'which': 27,
 'faculties': 28,
 'medicine': 29,
 'medical': 30,
 'peradeniya': 31,
 'for': 32,
 'sports': 33,
 'located': 34,
 'were': 35,
 'school': 36,
 'has': 37,
 'institute': 38,
 'road': 39,
 'library': 40,
 'two': 41,
 'oldest': 42,
 'students': 43,
 'other': 44,
 'chancellor': 45,
 'departments': 46,
 'house': 47,
 'arts': 48,
 'education': 49,
 'vice': 50,
 'studies': 51,
 'campus': 52,
 '1942': 53,
 'out': 54,
 'country': 55,
 'universities': 56,
 'affiliated': 57,
 'degrees': 58,
 'from': 59,
 'most': 60,
 'up': 61,
 'academic': 62,
 'postgraduate': 63,
 'an': 64,
 'along': 65,
 'hall': 66,
 'on': 67,
 'later': 68,
 'three': 69,
 'uoc': 70,
 '

In [8]:
input_sequences = []
for sentence in The_University_of_Colombo.split('\n'):
    token_list = tokenizer.texts_to_sequences([sentence])[0]
    for i in range(1, len(token_list)):
        sequence = token_list[:i+1]
        input_sequences.append(sequence)

In [9]:
input_sequences[:5]

[[1, 3], [1, 3, 2], [1, 3, 2, 7], [1, 3, 2, 7, 245], [1, 3, 2, 7, 245, 7]]

In [10]:
max_length = max([len(input_sequence) for input_sequence in input_sequences])
max_length

152

In [11]:
input_sequences = np.array(tf.keras.preprocessing.sequence.pad_sequences(input_sequences, maxlen=max_length, padding='pre'))


In [12]:
input_sequences[1]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 3, 2],
      dtype=int32)

In [13]:
X = input_sequences[:, :-1]
y = input_sequences[:, -1]

In [14]:
X[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
      dtype=int32)

In [15]:
y

array([  3,   2,   7, ..., 635,   4, 636], dtype=int32)

In [16]:
num_classes = len(tokenizer.word_index)+1

In [17]:
y = np.array(tf.keras.utils.to_categorical(y, num_classes=num_classes))

In [18]:
y[1]

array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [19]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Embedding(num_classes, 80, input_length=max_length-1))
model.add(tf.keras.layers.LSTM(100))
model.add(tf.keras.layers.Dense(num_classes, activation='softmax'))

In [20]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 151, 80)           50960     
                                                                 
 lstm (LSTM)                 (None, 100)               72400     
                                                                 
 dense (Dense)               (None, 637)               64337     
                                                                 
Total params: 187697 (733.19 KB)
Trainable params: 187697 (733.19 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [21]:
model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])


In [22]:
history = model.fit(X, y, epochs=100)

Epoch 1/100
70/70 [==============================] - 11s 120ms/step - loss: 5.8250 - accuracy: 0.0883
Epoch 2/100
70/70 [==============================] - 7s 106ms/step - loss: 5.3207 - accuracy: 0.0951
Epoch 3/100
70/70 [==============================] - 8s 120ms/step - loss: 5.2339 - accuracy: 0.1163
Epoch 4/100
70/70 [==============================] - 8s 120ms/step - loss: 5.1117 - accuracy: 0.1613
Epoch 5/100
70/70 [==============================] - 7s 105ms/step - loss: 4.9527 - accuracy: 0.1852
Epoch 6/100
70/70 [==============================] - 8s 119ms/step - loss: 4.7975 - accuracy: 0.1897
Epoch 7/100
70/70 [==============================] - 8s 116ms/step - loss: 4.6565 - accuracy: 0.2064
Epoch 8/100
70/70 [==============================] - 8s 112ms/step - loss: 4.5266 - accuracy: 0.2105
Epoch 9/100
70/70 [==============================] - 8s 121ms/step - loss: 4.4035 - accuracy: 0.2235
Epoch 10/100
70/70 [==============================] - 8s 110ms/step - loss: 4.2940 - accur

In [25]:
input_text = "university of colombo"
for i in range(10):
    token_list = tokenizer.texts_to_sequences([input_text])[0]
    token_list = tf.keras.preprocessing.sequence.pad_sequences([token_list], maxlen=max_length-1, padding='pre')
    predicted = np.argmax(model.predict(token_list), axis=-1)
    output_word = ""
    for word, index in tokenizer.word_index.items():
        if index == predicted:
            output_word = word
            break
    input_text += " " + output_word

print(input_text)

1/1 [==============================] - 0s 39ms/step
university of colombo library is a centrally administered network of libraries of the


In [26]:
model.save('new_model.h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
